# Generated by Django 6.0.4 on 2026-04-29 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miss', '0002_habit_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='task_date',
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='HabitDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miss.habit')),
            ],
        ),
    ]
